apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e2e4z8ka8-python
  janus-idp.io/tekton: e2e4z8ka8-python
  backstage.io/kubernetes-id: e2e4z8ka8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e2e4z8ka8-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
